In [4]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


C:\Users\vpp\Anaconda3\lib\site-packages\IPython\core\magics\pylab.py:159: UserWarning: pylab import has clobbered these variables: ['test', 'array', 'plotting', 'unique']
`%matplotlib` prevents importing * from pylab and numpy
  warn("pylab import has clobbered these variables: %s"  % clobbered +


In [5]:
from pandas import *
import numpy

In [10]:
def make_maze(w , h):
    vis = [[0] * w + [1] for _ in range(h)] + [[1] * (w + 1)]
    ver = [["10"] * w + ['1'] for _ in range(h)] + [[]]
    hor = [["11"] * w + ['1'] for _ in range(h + 1)]
 
    def walk(x, y):
        vis[y][x] = 1
 
        d = [(x - 1, y), (x, y + 1), (x + 1, y), (x, y - 1)]
        shuffle(d)
        for (xx, yy) in d:
            if vis[yy][xx]: continue
            if xx == x: hor[max(y, yy)][x] = "10"
            if yy == y: ver[y][max(x, xx)] = "00"
            walk(xx, yy)
 
    walk(numpy.random.randint(w), numpy.random.randint(h))
 
    s = ""
    for (a, b) in zip(hor, ver):
        s += ''.join(a + ['\n'] + b + ['\n'])
        
    M=[]
    for line in s.split("\n"):
        if line!="":
            R=[]
            for e in line:
                R.append(int(e))
            M.append(R)
    return M
 
maze=numpy.array(make_maze(8,8))
print(maze)
#imshow(maze)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1]
 [1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 0 1]
 [1 0 0 0 1 0 1 0 0 0 1 0 1 0 1 0 1]
 [1 1 1 0 1 0 1 1 1 0 1 0 1 0 1 0 1]
 [1 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 1]
 [1 0 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1]
 [1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1]
 [1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1]
 [1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1]
 [1 0 1 1 1 1 1 0 1 0 1 0 1 0 1 1 1]
 [1 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 1]
 [1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1]
 [1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
