In [2]:
%matplotlib inline

In [3]:
board=[0,0,0,0,0,0,0,0,0]
print(board)


if len(board)!=9:
    print("you did something wrong")

[0, 0, 0, 0, 0, 0, 0, 0, 0]


In [7]:
def showBoard(board):
    #your code here!
    print(board) #<- not enough, must be better!
showBoard(board)

[0, 0, 0, 0, 0, 0, 0, 0, 0]


In [6]:
def showBoard(board):
    C=[".","O","X"]
    print(C[board[0]],C[board[1]],C[board[2]])
    print(C[board[3]],C[board[4]],C[board[5]])
    print(C[board[6]],C[board[7]],C[board[8]])

showBoard([0,1,2,0,0,1,0,2,0])


. O X
. . O
. X .


In [11]:
board=numpy.random.choice([-1,0,1],(9))
print(board)

[ 1  1  1  1  0 -1 -1 -1  1]


In [12]:
def showBoard(board):
    C=[".","O","X"]
    #C={-1:"O",0:".",1:"X"}
    i=0
    for column in range(3):
        S=""
        for row in range(3):
            S=S+" "+C[board[i]]+" |"
            i=i+1
        print(S)
        print("---+---+---")
showBoard(board)

 O | O | O |
---+---+---
 O | . | X |
---+---+---
 X | X | O |
---+---+---


In [13]:
def emptyBoard():
    return [0,0,0,0,0,0,0,0,0]

def getAllLegalMoves(board):
    L=list()
    for i in range(9):
        if board[i]==0:
            L.append(i)
    return L

for i in range(10):
    board=numpy.random.choice([0,1,2],(9))
    print(board,getAllLegalMoves(board))

def isWinningBoard(board):
    if sum(board)==0:
        return False
    if board[0]==board[1] and board[1]==board[2]:
        return True
    if board[3]==board[4] and board[4]==board[5]:
        return True
    #...
    return False


[0 0 2 0 0 0 2 1 1] [0, 1, 3, 4, 5]
[0 1 1 2 0 2 1 2 1] [0, 4]
[2 2 1 0 1 1 2 0 1] [3, 7]
[0 2 2 1 1 1 0 1 0] [0, 6, 8]
[1 0 1 0 0 2 1 1 2] [1, 3, 4]
[1 0 2 2 2 1 2 1 2] [1]
[0 0 1 1 2 0 0 2 2] [0, 1, 5, 6]
[2 2 2 0 1 0 0 0 0] [3, 5, 6, 7, 8]
[0 0 2 1 1 0 0 0 2] [0, 1, 5, 6, 7]
[0 0 1 1 0 2 2 1 0] [0, 1, 4, 8]


In [27]:
# create empty board
#while not done:
#    show boaed
#    get input from current player
#    execute move of current player
#    switch player


In [ ]:
board=emptyBoard()
currentPlayer=1
C=[".","O","X"]
# Debugging
print(board,currentPlayer,isWinningBoard(board),getAllLegalMoves(board))
while True:
    showBoard(board)
    print("player "+C[currentPlayer]+" move:")
    choice=int(input())
    if choice in getAllLegalMoves(board):
        
        #insert 1 or 2 into board at location choice
        board[choice]=currentPlayer
        currentPlayer=3-currentPlayer
    else:
        print("this is your last warning")

[0, 0, 0, 0, 0, 0, 0, 0, 0] 1 False [0, 1, 2, 3, 4, 5, 6, 7, 8]
 . | . | . |
---+---+---
 . | . | . |
---+---+---
 . | . | . |
---+---+---
player O move:


In [32]:
board=numpy.random.choice([0,1,2],(9))
print(board)
print(board[[0,1,2]])

[1 2 0 0 0 2 1 1 0]
[1 2 0]


In [41]:
print(board)
sum(board)

[0, 0, 0, 0, 0, 1, 0, 0, 0]


1